---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Install python module and role dependencies
  - pip install -r requirements.txt
  - ansible-galaxy install -p tests/roles -r requirements-test.yml

  # Check ansible version
  - ansible --version

script:
  - set -e
  - export ANSIBLE_ROLES_PATH=$(cd ..; pwd)

  - echo "=====[round 0][Basic role syntax check]====="
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  - echo "=====[round 1][unset become_allow_same_user]====="
  - printf '' >ansible.cfg
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
  - ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

  - echo "=====[round 2][set become_allow_same_user to False]====="
  - printf '[privilege_escalation]\nbecome_allow_same_user=no' >ansible.cfg
  - ansible-playbook tests/test.yml -i tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
  - ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

  - echo "=====[round 3][set become_allow_same_user to True]====="
  - printf '[privilege_escalation]\nbecome_allow_same_user=True' >ansible.cfg
  - ansible-playbook tests/test.yml -i tests/inventory
  - true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
  - ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
  - true && ! ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
  - ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
  - true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
