---
- name: try force disable become
  run_once: True
  when:
  - inventory_hostname == ansible_play_hosts[0]
  - ( [ groups.all
        | map('extract', hostvars, 'ansible_become')
        | map('d', False)
        | map('bool')
        | unique ]
    )
    | difference([[False]])
    | first
    | d([])
    | list
    | length == 1
    or ( not lookup('config', 'BECOME_ALLOW_SAME_USER')
         and [ groups.all
               | map('extract', hostvars, 'ansible_become_user')
               | map('d', omit)
               | unique ]
             | difference([[omit]])
             | first
             | d([])
             | list
             | length == 1 )
  become: False
  become_user: --FAKE::::USER={{ omit }}
  vars:
  - ansible_become: False
  - ansible_become_user: --FAKE::::USER={{ omit }}
  assert:
    that: "not ansible_become or
           ( not lookup('config', 'BECOME_ALLOW_SAME_USER')
             and ansible_become_user == ('--FAKE::::USER=' + omit)
           )
          "
