---
- name: try force disable become
  run_once: True
  when:
  - inventory_hostname == ansible_play_hosts[0]
  - ( [ groups.all
        | map('extract', hostvars, 'ansible_become')
        | map('d', False)
        | map('bool')
        | unique ]
    )
    | difference([[False]])
    | first
    | d([])
    | list
    | length == 1
    or ( local_ansible_config['privilege_escalation/become_allow_same_user']
         | d(False)
         | bool == False
         and [ groups.all
               | map('extract', hostvars, 'ansible_become_user')
               | map('d', omit)
               | unique ]
             | difference([[omit]])
             | first
             | d([])
             | list
             | length == 1 )
  become: False
  become_user: --FAKE::::USER={{ omit }}
  vars:
  - ansible_become: False
  - ansible_become_user: --FAKE::::USER={{ omit }}
  assert:
    that: "ansible_become == False or
           ( local_ansible_config['privilege_escalation/become_allow_same_user']
             | d(False)
             | bool == False and
             ansible_become_user == ('--FAKE::::USER=' + omit)
           )
          "
