---
name: ci workflow
"on": push

env:
  ANSIBLE_ROLES_PATH: "..:tests/roles"

jobs:
  test-job:
    name: test the role
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: print versions
      run: |
        python3 --version
        pip3 --version
        ansible --version
        ansible-galaxy --version

    - name: prepare tests
      run: |
        pip3 install -r requirements.txt
        ansible-galaxy install -p tests/roles -r requirements.yml

    - name: syntax check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    - name: unset become_allow_same_user
      run: |
        printf '' >ansible.cfg
        ansible-playbook tests/test.yml -i tests/inventory
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
        ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

    - name: set become_allow_same_user to False
      run: |
        printf '[privilege_escalation]\nbecome_allow_same_user=no' >ansible.cfg
        ansible-playbook tests/test.yml -i tests/inventory
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
        ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

    - name: set become_allow_same_user to True
      run: |
        printf '[privilege_escalation]\nbecome_allow_same_user=True' >ansible.cfg
        ansible-playbook tests/test.yml -i tests/inventory
        true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes -e ansible_become_user=x
        ANSIBLE_BECOME=True ansible-playbook tests/test.yml -i tests/inventory -e ansible_become_user=x
        true && ! ANSIBLE_BECOME_USER=x ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes
        ansible-playbook tests/test.yml -i tests/inventory --become -e ansible_become_user=x
        true && ! ansible-playbook tests/test.yml -i tests/inventory -e ansible_become=yes --become-user=x

  lint-job:
    name: lint codes
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: prepare lint
      run: |
        pip3 install -r requirements.txt
        pip3 install ansible-lint
        ansible-lint --version
        ansible-galaxy install -p tests/roles -r requirements.yml
    - name: lint
      run: ansible-lint --show-relpath --exclude tests/roles

  deploy-job:
    name: deploy the role on tag
    runs-on: ubuntu-22.04
    needs: [test-job, lint-job]
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: publish the role to Galaxy
      uses: robertdebock/galaxy-action@1.2.1
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
        git_branch: ${{ github.ref_name }}
